# -*- coding: utf-8 -*-
"""simulasyonpull.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-5g-dWzMX2IOb2h_WM_Y5YnlMH9oSvnx
"""

!pip install simpy

"""
Beer Production System – SimPy Simulation
==========================================

COMBINATION ALGORITHM
─────────────────────
A "combination" is a fully pre-enumerated route from Silo to Fermentation Tank:

    Silo → MaltLine → Mill → Mashing[i]
         → Lautering[i] → Prewort[i] → Boiling[i]   (lane i = mashing index)
         → Cooler[j] → FermLine[k] → FermTank (Small | Large)

All 1-to-1 lanes (Mashing → Lautering → Prewort → Boiling) are implicit in
the mashing index, so no separate choice is needed for those stages.

FLAG ALGORITHM  (identical rule applied to the FULL path)
──────────────
    combo.flag = 1  if  ANY equipment in the combo is currently busy.
    combo.flag = 0  only when ALL equipment in the combo is free.

Equipment is freed in stages as each step completes:
    ① MaltLine done   → free Silo, MaltLine
    ② Mill done       → free Mill
    ③ Mashing done    → free Mashing, Lautering, Prewort, Boiling (entire lane)
    ④ Cooling done    → free Cooler
    ⑤ FermLine done   → free FermLine  → combo.flag becomes 0

BATCH CREATION RULE
───────────────────
    1. Find the first available fermentation tank (Small first, then Large).
    2. Collect all combinations whose flag==0 matching that tank_type.
    3. Pick the combination with MINIMUM total processing time.
    4. Lock all equipment in the combination → combo.flag = 1.
    5. Pre-allocate one slot in the target tank.
    6. Spawn the batch pipeline process.
    7. Retry immediately (timeout=0) to fill remaining free slots.

TOTAL COMBINATIONS
──────────────────
    upstream (Silo x MaltLine x Mill x Mashing) : 85
    x Coolers (4) x FermLines (2) x TankTypes (2) = 1 360 combinations
"""

import simpy
import logging
from dataclasses import dataclass, field
from typing import Optional, List, Dict, Tuple

logging.basicConfig(level=logging.INFO, format="%(message)s")
log = logging.getLogger(__name__)


# ===========================================================================
#  CONFIGURATION
# ===========================================================================
CONFIG: Dict = {
    # Processing times (hours)
    "malt_line_transfer_time":  2,
    "mill_processing_time":     3,
    "mashing_time":            10,
    "lautering_time":           8,
    "prewort_time":             5,
    "boiling_time":            15,
    "cooling_time":             6,
    "ferm_line_time":           2,

    # Fermentation tanks
    "small_tank_count":        48,
    "small_tank_capacity":      4,   # batches per small tank
    "large_tank_count":        37,
    "large_tank_capacity":      8,   # batches per large tank
    "tank_cycle_days":         15,   # days from tank-full until emptied

    # Simulation
    "hours_per_day":           24,
    "batch_check_interval":     0.5,
    "sim_duration":           500,
    "verbose":               True,
}


# ===========================================================================
#  TOPOLOGY
# ===========================================================================
CONNECTIONS: Dict = {
    "silo_to_malt": {
        "M": ["Cimbria", "Kunzel", "Alapros"],
        "N": ["Cimbria", "Kunzel", "Alapros"],
        "O": ["Cimbria", "Kunzel", "Alapros"],
        "P": ["Cimbria", "Kunzel", "Alapros"],
        "R": ["Cimbria", "Kunzel", "Alapros"],
    },
    "malt_to_mill": {
        "Cimbria": ["Millstar", "Powermill"],
        "Kunzel":  ["Millstar", "Powermill", "Variomill"],
        "Alapros": ["Powermill", "Variomill"],
    },
    "mill_to_mashing": {
        "Millstar":  [1, 2],
        "Powermill": [2, 3, 4],
        "Variomill": [4, 5],
    },
    # Mashing i -> Lautering i -> Prewort i -> Boiling i  (fixed 1-to-1 lanes)
    "boiling_to_cooler":  {i: [1, 2, 3, 4] for i in range(1, 6)},
    "cooler_to_fermline": {i: [1, 2]        for i in range(1, 5)},
    "fermline_to_tank":   {i: ["Small", "Large"] for i in range(1, 3)},
}


# ===========================================================================
#  DATA CLASSES
# ===========================================================================

@dataclass
class RouteCombo:
    """
    A fully pre-enumerated production route from Silo to FermTank type.

        Silo -> MaltLine -> Mill -> Mashing[i]
             -> Lautering[i] -> Prewort[i] -> Boiling[i]
             -> Cooler[j] -> FermLine[k] -> FermTank[tank_type]

    flag : int
        0 = all equipment in this combo is free  (batch can be assigned)
        1 = at least one equipment in this combo is busy (combo blocked)

    The flag is derived live from the EquipmentFlag objects at every
    equipment state change via _refresh_combo_flags().
    """
    combo_id:     int
    silo:         str
    malt_line:    str
    mill:         str
    mashing_id:   int          # also = lautering_id = prewort_id = boiling_id
    cooler_id:    int
    ferm_line_id: int
    tank_type:    str          # "Small" or "Large"
    flag:         int = field(default=0, compare=False, repr=False)

    @property
    def lautering_id(self) -> int: return self.mashing_id
    @property
    def prewort_id(self)   -> int: return self.mashing_id
    @property
    def boiling_id(self)   -> int: return self.mashing_id

    @property
    def all_equipment_keys(self) -> List[str]:
        """
        All equipment keys that must be free for combo.flag == 0.
        Covers the full path from Silo to FermLine.
        """
        return [
            f"Silo-{self.silo}",
            f"MaltLine-{self.malt_line}",
            f"Mill-{self.mill}",
            f"Mashing-{self.mashing_id}",
            f"Lautering-{self.mashing_id}",
            f"Prewort-{self.mashing_id}",
            f"Boiling-{self.mashing_id}",
            f"Cooler-{self.cooler_id}",
            f"FermLine-{self.ferm_line_id}",
        ]

    @property
    def total_time(self) -> float:
        """Sum of all processing times (used as selection key)."""
        return (
            CONFIG["malt_line_transfer_time"] +
            CONFIG["mill_processing_time"]    +
            CONFIG["mashing_time"]            +
            CONFIG["lautering_time"]          +
            CONFIG["prewort_time"]            +
            CONFIG["boiling_time"]            +
            CONFIG["cooling_time"]            +
            CONFIG["ferm_line_time"]
        )

    def __str__(self) -> str:
        return (
            f"C{self.combo_id:04d}: "
            f"{self.silo}->{self.malt_line}->{self.mill}->"
            f"Mash{self.mashing_id}->Laut{self.lautering_id}->"
            f"PW{self.prewort_id}->Boil{self.boiling_id}->"
            f"Cool{self.cooler_id}->FL{self.ferm_line_id}->"
            f"{self.tank_type}"
        )


@dataclass
class EquipmentFlag:
    """
    Runtime status flag for a single piece of equipment.

    busy              : True while a batch is being processed here.
    batches_processed : incremented each time a batch starts at this equipment.
    current_batch_id  : ID of the batch currently in this equipment (or None).
    """
    name:              str
    busy:              bool = False
    batches_processed: int  = 0
    current_batch_id:  Optional[int] = None

    def set_busy(self, batch_id: int) -> None:
        self.busy             = True
        self.current_batch_id = batch_id
        self.batches_processed += 1

    def set_free(self) -> None:
        self.busy             = False
        self.current_batch_id = None


@dataclass
class TankSlot:
    """
    One individual fermentation tank.

    allocated  : slots reserved at batch-creation time (pre-allocation).
    arrived    : batches that have physically entered the tank.
    fermenting : True once tank is full (no more pre-allocation allowed).
    cycles_done: number of completed fermentation cycles.
    """
    tank_type:   str
    tank_id:     int
    capacity:    int
    allocated:   int  = 0
    arrived:     int  = 0
    fermenting:  bool = False
    cycles_done: int  = 0

    @property
    def available_space(self) -> int:
        return 0 if self.fermenting else (self.capacity - self.allocated)

    @property
    def label(self) -> str:
        return f"{self.tank_type}-T{self.tank_id:02d}"

    def allocate(self) -> None:
        self.allocated += 1
        if self.allocated >= self.capacity:
            self.fermenting = True

    def batch_arrived(self) -> bool:
        """Mark one batch physically present. Returns True if tank is now full."""
        self.arrived += 1
        return self.arrived >= self.capacity

    def empty(self) -> None:
        self.allocated   = 0
        self.arrived     = 0
        self.fermenting  = False
        self.cycles_done += 1


@dataclass
class Batch:
    """A single production batch travelling through the brewery."""
    batch_id:      int
    combo:         RouteCombo
    tank:          TankSlot
    creation_time: float
    current_stage: str = "created"
    history:       List[Tuple[float, str]] = field(default_factory=list)
    completed:     bool = False

    def advance(self, stage: str, now: float) -> None:
        self.current_stage = stage
        self.history.append((now, stage))
        if CONFIG["verbose"]:
            log.info(f"  [t={now:8.2f}h]  Batch {self.batch_id:03d}  >>  {stage}")


# ===========================================================================
#  BEER PRODUCTION SYSTEM
# ===========================================================================

class BeerProductionSystem:
    """
    Full brewery Discrete-Event Simulation using SimPy.

    Routing decisions are made at batch-creation time by selecting the
    best free RouteCombo covering the FULL path (Silo to FermTank type).
    Conflict prevention is handled entirely through the combination flag
    system — no SimPy Resource queuing is needed.
    SimPy timeouts represent actual processing durations at each step.

    Key attributes
    --------------
    combinations      : List[RouteCombo]        all pre-enumerated full routes
    eq_flags          : Dict[str, EquipmentFlag] per-equipment busy/free status
    small_tanks       : Dict[int, TankSlot]
    large_tanks       : Dict[int, TankSlot]
    completed_batches : List[Batch]
    """

    def __init__(self, env: simpy.Environment, cfg: Dict = CONFIG) -> None:
        self.env = env
        self.cfg = cfg
        self.completed_batches: List[Batch] = []
        self._batch_counter: int = 0

        self._build_equipment_flags()
        self._build_tanks()
        self._generate_combinations()

        log.info("=" * 72)
        log.info("  Beer Production System initialised")
        log.info("=" * 72)
        log.info(f"  Total combinations : {len(self.combinations)}")
        log.info(f"  Small tanks        : {cfg['small_tank_count']} x "
                 f"{cfg['small_tank_capacity']} batches = "
                 f"{cfg['small_tank_count'] * cfg['small_tank_capacity']} slots")
        log.info(f"  Large tanks        : {cfg['large_tank_count']} x "
                 f"{cfg['large_tank_capacity']} batches = "
                 f"{cfg['large_tank_count'] * cfg['large_tank_capacity']} slots")
        log.info(f"  Tank cycle         : {cfg['tank_cycle_days']} days "
                 f"({cfg['tank_cycle_days'] * cfg['hours_per_day']} h)")
        log.info("=" * 72 + "\n")

    # -----------------------------------------------------------------------
    #  BUILDERS
    # -----------------------------------------------------------------------

    def _build_equipment_flags(self) -> None:
        """Create one EquipmentFlag per equipment instance."""
        self.eq_flags: Dict[str, EquipmentFlag] = {}

        for s in ["M", "N", "O", "P", "R"]:
            self.eq_flags[f"Silo-{s}"] = EquipmentFlag(f"Silo-{s}")

        for ml in ["Cimbria", "Kunzel", "Alapros"]:
            self.eq_flags[f"MaltLine-{ml}"] = EquipmentFlag(f"MaltLine-{ml}")

        for m in ["Millstar", "Powermill", "Variomill"]:
            self.eq_flags[f"Mill-{m}"] = EquipmentFlag(f"Mill-{m}")

        for i in range(1, 6):
            self.eq_flags[f"Mashing-{i}"]   = EquipmentFlag(f"Mashing-{i}")
            self.eq_flags[f"Lautering-{i}"] = EquipmentFlag(f"Lautering-{i}")
            self.eq_flags[f"Prewort-{i}"]   = EquipmentFlag(f"Prewort-{i}")
            self.eq_flags[f"Boiling-{i}"]   = EquipmentFlag(f"Boiling-{i}")

        for i in range(1, 5):
            self.eq_flags[f"Cooler-{i}"] = EquipmentFlag(f"Cooler-{i}")

        for i in range(1, 3):
            self.eq_flags[f"FermLine-{i}"] = EquipmentFlag(f"FermLine-{i}")

    def _build_tanks(self) -> None:
        """Instantiate all individual fermentation tanks."""
        self.small_tanks: Dict[int, TankSlot] = {
            i: TankSlot("Small", i, self.cfg["small_tank_capacity"])
            for i in range(1, self.cfg["small_tank_count"] + 1)
        }
        self.large_tanks: Dict[int, TankSlot] = {
            i: TankSlot("Large", i, self.cfg["large_tank_capacity"])
            for i in range(1, self.cfg["large_tank_count"] + 1)
        }

    def _generate_combinations(self) -> None:
        """
        Enumerate every valid full route:

            Silo -> MaltLine -> Mill -> Mashing[i]
                 -> Lautering[i] -> Prewort[i] -> Boiling[i]
                 -> Cooler[j] -> FermLine[k] -> FermTank[type]

        Stored in self.combinations (list) and self._combo_index (dict).
        """
        self.combinations: List[RouteCombo] = []
        cid = 0

        for silo, malt_opts in CONNECTIONS["silo_to_malt"].items():
            for malt_line in malt_opts:
                for mill in CONNECTIONS["malt_to_mill"][malt_line]:
                    for mashing_id in CONNECTIONS["mill_to_mashing"][mill]:
                        for cooler_id in CONNECTIONS["boiling_to_cooler"][mashing_id]:
                            for ferm_line_id in CONNECTIONS["cooler_to_fermline"][cooler_id]:
                                for tank_type in CONNECTIONS["fermline_to_tank"][ferm_line_id]:
                                    self.combinations.append(
                                        RouteCombo(
                                            combo_id=cid,
                                            silo=silo,
                                            malt_line=malt_line,
                                            mill=mill,
                                            mashing_id=mashing_id,
                                            cooler_id=cooler_id,
                                            ferm_line_id=ferm_line_id,
                                            tank_type=tank_type,
                                        )
                                    )
                                    cid += 1

        self._combo_index: Dict[int, RouteCombo] = {
            c.combo_id: c for c in self.combinations
        }
        log.info(f"  Generated {len(self.combinations)} route combinations.")

    # -----------------------------------------------------------------------
    #  COMBINATION FLAG FUNCTIONS
    # -----------------------------------------------------------------------

    def _refresh_combo_flags(self) -> None:
        """
        Recompute every combination's flag from current EquipmentFlag states.

            combo.flag = 1  iff  ANY equipment in all_equipment_keys is busy.
            combo.flag = 0  iff  ALL equipment in all_equipment_keys is free.

        Called after every equipment state change (set_busy / set_free).
        """
        for combo in self.combinations:
            combo.flag = int(
                any(self.eq_flags[k].busy for k in combo.all_equipment_keys)
            )

    def _get_free_combinations(self, tank_type: str) -> List[RouteCombo]:
        """
        Refresh all flags and return combinations where:
            - combo.flag == 0  (all equipment free), AND
            - combo.tank_type  matches the requested type.
        """
        self._refresh_combo_flags()
        return [
            c for c in self.combinations
            if c.flag == 0 and c.tank_type == tank_type
        ]

    # -----------------------------------------------------------------------
    #  EQUIPMENT LOCK / STAGED RELEASE FUNCTIONS
    # -----------------------------------------------------------------------

    def _lock_combo(self, combo: RouteCombo, batch_id: int) -> None:
        """
        Mark every equipment item in the combination as busy at batch creation.
        Sets combo.flag = 1 and blocks all overlapping combinations.
        """
        for key in combo.all_equipment_keys:
            self.eq_flags[key].set_busy(batch_id)
        combo.flag = 1

    def _release_stage_1(self, combo: RouteCombo) -> None:
        """
        Stage 1 – after MaltLine transfer completes.
        Frees: Silo, MaltLine
        """
        self.eq_flags[f"Silo-{combo.silo}"].set_free()
        self.eq_flags[f"MaltLine-{combo.malt_line}"].set_free()
        self._refresh_combo_flags()

    def _release_stage_2(self, combo: RouteCombo) -> None:
        """Stage 2 – after Mill completes.  Frees: Mill."""
        self.eq_flags[f"Mill-{combo.mill}"].set_free()
        self._refresh_combo_flags()

    def _release_stage_3(self, combo: RouteCombo) -> None:
        """
        Stage 3 – after Mashing completes.
        Frees: Mashing, Lautering, Prewort, Boiling (entire lane i).
        The full lane is freed here because these steps run sequentially
        and exclusively on the same batch.
        """
        lane = combo.mashing_id
        self.eq_flags[f"Mashing-{lane}"].set_free()
        self.eq_flags[f"Lautering-{lane}"].set_free()
        self.eq_flags[f"Prewort-{lane}"].set_free()
        self.eq_flags[f"Boiling-{lane}"].set_free()
        self._refresh_combo_flags()

    def _release_stage_4(self, combo: RouteCombo) -> None:
        """Stage 4 – after Cooling completes.  Frees: Cooler."""
        self.eq_flags[f"Cooler-{combo.cooler_id}"].set_free()
        self._refresh_combo_flags()

    def _release_stage_5(self, combo: RouteCombo) -> None:
        """
        Stage 5 (final) – after FermLine transfer completes.
        Frees: FermLine.  combo.flag becomes 0 (all equipment now free).
        """
        self.eq_flags[f"FermLine-{combo.ferm_line_id}"].set_free()
        self._refresh_combo_flags()

    # -----------------------------------------------------------------------
    #  TANK MANAGEMENT FUNCTIONS
    # -----------------------------------------------------------------------

    def _find_available_tank(self, tank_type: str) -> Optional[TankSlot]:
        """
        Return the lowest-indexed tank of the given type with a free slot.
        Tanks are filled sequentially (tank N is filled before tank N+1).
        """
        tanks = self.small_tanks if tank_type == "Small" else self.large_tanks
        for tank in tanks.values():
            if tank.available_space > 0:
                return tank
        return None

    def _fermentation_cycle(self, tank: TankSlot):
        """
        SimPy generator: wait tank_cycle_days hours, then empty the tank.
        Triggered when the last batch physically arrives in a full tank.
        """
        cycle_hours = self.cfg["tank_cycle_days"] * self.cfg["hours_per_day"]
        log.info(
            f"\n  [t={self.env.now:8.2f}h]  {tank.label} FULL "
            f"({tank.capacity} batches). "
            f"Fermentation starts ({self.cfg['tank_cycle_days']} days)."
        )
        yield self.env.timeout(cycle_hours)
        tank.empty()
        log.info(
            f"\n  [t={self.env.now:8.2f}h]  {tank.label} emptied "
            f"(cycle {tank.cycles_done} done). Ready for new batches.\n"
        )

    # -----------------------------------------------------------------------
    #  EQUIPMENT PROCESS FUNCTIONS
    # -----------------------------------------------------------------------
    # Each function represents one processing step.
    # No SimPy Resource queuing is used — the combination flag system
    # guarantees no two batches ever share the same equipment simultaneously.

    def _step_malt_line(self, batch: Batch):
        """Silo dispenses + MaltLine transfers.  Stage-1 release on done."""
        combo = batch.combo
        batch.advance(
            f"Silo-{combo.silo} -> MaltLine-{combo.malt_line}", self.env.now
        )
        yield self.env.timeout(self.cfg["malt_line_transfer_time"])
        self._release_stage_1(combo)

    def _step_mill(self, batch: Batch):
        """Mill grinds malt.  Stage-2 release on done."""
        combo = batch.combo
        batch.advance(f"Mill-{combo.mill}", self.env.now)
        yield self.env.timeout(self.cfg["mill_processing_time"])
        self._release_stage_2(combo)

    def _step_mashing(self, batch: Batch):
        """Mashing.  Stage-3 release on done (frees entire lane)."""
        combo = batch.combo
        batch.advance(f"Mashing-{combo.mashing_id}", self.env.now)
        yield self.env.timeout(self.cfg["mashing_time"])
        self._release_stage_3(combo)

    def _step_lautering(self, batch: Batch):
        """Lautering (lane freed at stage-3; timeout only)."""
        batch.advance(f"Lautering-{batch.combo.lautering_id}", self.env.now)
        yield self.env.timeout(self.cfg["lautering_time"])

    def _step_prewort(self, batch: Batch):
        """Pre-wort collection."""
        batch.advance(f"Prewort-{batch.combo.prewort_id}", self.env.now)
        yield self.env.timeout(self.cfg["prewort_time"])

    def _step_boiling(self, batch: Batch):
        """Boiling."""
        batch.advance(f"Boiling-{batch.combo.boiling_id}", self.env.now)
        yield self.env.timeout(self.cfg["boiling_time"])

    def _step_cooling(self, batch: Batch):
        """Cooling.  Stage-4 release on done."""
        combo = batch.combo
        batch.advance(f"Cooler-{combo.cooler_id}", self.env.now)
        yield self.env.timeout(self.cfg["cooling_time"])
        self._release_stage_4(combo)

    def _step_ferm_line(self, batch: Batch):
        """Fermentation line transfer.  Stage-5 (final) release on done."""
        combo = batch.combo
        batch.advance(f"FermLine-{combo.ferm_line_id}", self.env.now)
        yield self.env.timeout(self.cfg["ferm_line_time"])
        self._release_stage_5(combo)

    # -----------------------------------------------------------------------
    #  BATCH PIPELINE
    # -----------------------------------------------------------------------

    def batch_pipeline(self, batch: Batch):
        """
        Drive one batch through all production stages in order.

        Stage releases free equipment at the earliest possible moment
        so overlapping combinations can reuse that equipment immediately:

            _step_malt_line done  -> Silo + MaltLine freed  (stage 1)
            _step_mill done       -> Mill freed              (stage 2)
            _step_mashing done    -> Mashing + Laut + PW + Boil freed  (stage 3)
            _step_cooling done    -> Cooler freed            (stage 4)
            _step_ferm_line done  -> FermLine freed          (stage 5)
                                     combo.flag -> 0
        """
        # Upstream (combination-locked, staged releases)
        yield from self._step_malt_line(batch)    # stage 1 release
        yield from self._step_mill(batch)          # stage 2 release
        yield from self._step_mashing(batch)       # stage 3 release

        # Downstream lane (lane already freed at stage 3; timeouts only)
        yield from self._step_lautering(batch)
        yield from self._step_prewort(batch)
        yield from self._step_boiling(batch)

        # Shared downstream equipment
        yield from self._step_cooling(batch)       # stage 4 release
        yield from self._step_ferm_line(batch)     # stage 5 release -> combo free

        # Enter fermentation tank
        tank = batch.tank
        batch.advance(
            f"Entered {tank.label} ({batch.combo.tank_type} fermentation)",
            self.env.now,
        )
        if tank.batch_arrived():
            # Tank physically full -> start fermentation cycle
            self.env.process(self._fermentation_cycle(tank))

        batch.completed = True
        self.completed_batches.append(batch)
        if CONFIG["verbose"]:
            lead = self.env.now - batch.creation_time
            log.info(
                f"  [DONE] Batch {batch.batch_id:03d}  lead time = {lead:.2f} h\n"
            )

    # -----------------------------------------------------------------------
    #  BATCH SOURCE
    # -----------------------------------------------------------------------

    def batch_source(self):
        """
        Event-driven batch creation loop.

        Each iteration:
          1. Find first available tank (Small first, then Large).
          2. Get all combinations with flag==0 for that tank_type.
          3. Pick the minimum-total-time combination.
          4. Lock all equipment  ->  combo.flag = 1.
          5. Pre-allocate one tank slot.
          6. Spawn batch_pipeline.
          7. timeout(0) to immediately retry for the next free slot.
        If no tank or no free combo: wait batch_check_interval hours.
        """
        while True:
            tank = self._find_available_tank("Small")
            if tank is None:
                tank = self._find_available_tank("Large")
            if tank is None:
                yield self.env.timeout(self.cfg["batch_check_interval"])
                continue

            free_combos = self._get_free_combinations(tank.tank_type)
            if not free_combos:
                yield self.env.timeout(self.cfg["batch_check_interval"])
                continue

            best_combo = min(free_combos, key=lambda c: c.total_time)

            self._batch_counter += 1
            batch = Batch(
                batch_id=self._batch_counter,
                combo=best_combo,
                tank=tank,
                creation_time=self.env.now,
            )

            self._lock_combo(best_combo, self._batch_counter)
            tank.allocate()

            log.info(
                f"\n>>> [t={self.env.now:8.2f}h]  Batch {self._batch_counter:03d} created\n"
                f"    Route : {best_combo}\n"
                f"    Tank  : {tank.label}  "
                f"({tank.allocated}/{tank.capacity} allocated, "
                f"{'FULL' if tank.fermenting else 'open'})"
            )

            self.env.process(self.batch_pipeline(batch))
            yield self.env.timeout(0)

    # -----------------------------------------------------------------------
    #  RUN
    # -----------------------------------------------------------------------

    def run(self) -> None:
        self.env.process(self.batch_source())
        self.env.run(until=self.cfg["sim_duration"])

    # -----------------------------------------------------------------------
    #  REPORTING
    # -----------------------------------------------------------------------

    def print_summary(self) -> None:
        done    = len(self.completed_batches)
        small_c = sum(1 for b in self.completed_batches if b.tank.tank_type == "Small")
        large_c = sum(1 for b in self.completed_batches if b.tank.tank_type == "Large")

        print("\n" + "=" * 72)
        print("  SIMULATION SUMMARY")
        print("=" * 72)
        dur_h = self.cfg["sim_duration"]
        dur_d = dur_h / self.cfg["hours_per_day"]
        print(f"  Sim duration           : {dur_h} h  ({dur_d:.1f} days)")
        print(f"  Batches completed      : {done}  "
              f"(Small-tank: {small_c}  Large-tank: {large_c})")
        print(f"  Batches in pipeline    : {self._batch_counter - done}")
        print(f"  Total combinations     : {len(self.combinations)}")

        # Combination usage
        combo_use: Dict[int, int] = {}
        for b in self.completed_batches:
            cid = b.combo.combo_id
            combo_use[cid] = combo_use.get(cid, 0) + 1
        print(f"\n  Distinct combinations used : {len(combo_use)}")
        print("  Top-5 combinations by usage:")
        for cid, count in sorted(combo_use.items(),
                                  key=lambda x: x[1], reverse=True)[:5]:
            print(f"    {self._combo_index[cid]}  ->  {count} batches")

        # Equipment utilisation
        groups = {
            "Silos"      : [f"Silo-{s}"      for s in ["M","N","O","P","R"]],
            "Malt Lines" : [f"MaltLine-{m}"  for m in ["Cimbria","Kunzel","Alapros"]],
            "Mills"      : [f"Mill-{m}"      for m in ["Millstar","Powermill","Variomill"]],
            "Mashing"    : [f"Mashing-{i}"   for i in range(1, 6)],
            "Lautering"  : [f"Lautering-{i}" for i in range(1, 6)],
            "Prewort"    : [f"Prewort-{i}"   for i in range(1, 6)],
            "Boiling"    : [f"Boiling-{i}"   for i in range(1, 6)],
            "Coolers"    : [f"Cooler-{i}"    for i in range(1, 5)],
            "Ferm Lines" : [f"FermLine-{i}"  for i in range(1, 3)],
        }
        print("\n  Equipment utilisation (batches processed):")
        for group, keys in groups.items():
            vals = ", ".join(
                f"{k.split('-', 1)[1]}:{self.eq_flags[k].batches_processed}"
                for k in keys
            )
            print(f"    {group:<13}: {vals}")

        # Tank status
        print("\n  Fermentation tank status (used tanks only):")
        for tanks in (self.small_tanks, self.large_tanks):
            for t in tanks.values():
                if t.allocated > 0 or t.cycles_done > 0:
                    print(
                        f"    {t.label}  allocated={t.allocated}  "
                        f"arrived={t.arrived}  "
                        f"fermenting={t.fermenting}  "
                        f"cycles_done={t.cycles_done}"
                    )

        # Lead times
        if self.completed_batches:
            lts = [b.history[-1][0] - b.creation_time
                   for b in self.completed_batches]
            print(
                f"\n  Lead time  min/avg/max : "
                f"{min(lts):.1f} / {sum(lts)/len(lts):.1f} / {max(lts):.1f}  h"
            )
        print("=" * 72)


# ===========================================================================
#  ENTRY POINT
# ===========================================================================
if __name__ == "__main__":
    env    = simpy.Environment()
    system = BeerProductionSystem(env, CONFIG)
    system.run()
    system.print_summary()